/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@repo/lib/client';
import fetch from '@repo/lib/client';
import type {
  AddPet400,
  AddPet422,
  AddPetMutationRequest,
  AddPetMutationResponse,
} from '../../model/pet/AddPet.ts';

export function getAddPetUrl() {
  const res = { method: 'POST', url: `/pet` as const };
  return res;
}

/**
 * @description Add a new pet to the store.
 * @summary Add a new pet to the store.
 * {@link /pet}
 */
export async function addPet(
  data: AddPetMutationRequest,
  config: Partial<RequestConfig<AddPetMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AddPetMutationResponse,
    ResponseErrorConfig<AddPet400 | AddPet422>,
    AddPetMutationRequest
  >({ method: 'POST', url: getAddPetUrl().url.toString(), data: requestData, ...requestConfig });
  return res.data;
}
