/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@repo/lib/client';
import fetch from '@repo/lib/client';
import type {
  DeletePet400,
  DeletePetHeaderParams,
  DeletePetMutationResponse,
  DeletePetPathParams,
} from '../../model/pet/DeletePet.ts';

export function getDeletePetUrl({ petId }: { petId: DeletePetPathParams['petId'] }) {
  const res = { method: 'DELETE', url: `/pet/${petId}` as const };
  return res;
}

/**
 * @description Delete a pet.
 * @summary Deletes a pet.
 * {@link /pet/:petId}
 */
export async function deletePet(
  { petId }: { petId: DeletePetPathParams['petId'] },
  headers?: DeletePetHeaderParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<DeletePetMutationResponse, ResponseErrorConfig<DeletePet400>, unknown>({
    method: 'DELETE',
    url: getDeletePetUrl({ petId }).url.toString(),
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}
