/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@repo/lib/client';
import fetch from '@repo/lib/client';
import type {
  UpdatePetWithForm400,
  UpdatePetWithFormMutationResponse,
  UpdatePetWithFormPathParams,
  UpdatePetWithFormQueryParams,
} from '../../model/pet/UpdatePetWithForm.ts';

export function getUpdatePetWithFormUrl({
  petId,
}: {
  petId: UpdatePetWithFormPathParams['petId'];
}) {
  const res = { method: 'POST', url: `/pet/${petId}` as const };
  return res;
}

/**
 * @description Updates a pet resource based on the form data.
 * @summary Updates a pet in the store with form data.
 * {@link /pet/:petId}
 */
export async function updatePetWithForm(
  { petId }: { petId: UpdatePetWithFormPathParams['petId'] },
  params?: UpdatePetWithFormQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    UpdatePetWithFormMutationResponse,
    ResponseErrorConfig<UpdatePetWithForm400>,
    unknown
  >({
    method: 'POST',
    url: getUpdatePetWithFormUrl({ petId }).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
