/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from '@kubb/plugin-client/clients/axios';
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios';
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { findPetsByStatus } from '../../api/pet/findPetsByStatus.ts';
import type {
  FindPetsByStatus400,
  FindPetsByStatusQueryParams,
  FindPetsByStatusQueryResponse,
} from '../../model/pet/FindPetsByStatus.ts';

export const findPetsByStatusQueryKey = (params: FindPetsByStatusQueryParams) =>
  [{ url: '/pet/findByStatus' }, ...(params ? [params] : [])] as const;

export type FindPetsByStatusQueryKey = ReturnType<typeof findPetsByStatusQueryKey>;

export function findPetsByStatusQueryOptions(
  params: FindPetsByStatusQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByStatusQueryKey(params);
  return queryOptions<
    FindPetsByStatusQueryResponse,
    ResponseErrorConfig<FindPetsByStatus400>,
    FindPetsByStatusQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return findPetsByStatus(params, config);
    },
  });
}

/**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * {@link /pet/findByStatus}
 */
export function useFindPetsByStatus<
  TData = FindPetsByStatusQueryResponse,
  TQueryData = FindPetsByStatusQueryResponse,
  TQueryKey extends QueryKey = FindPetsByStatusQueryKey,
>(
  params: FindPetsByStatusQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        FindPetsByStatusQueryResponse,
        ResponseErrorConfig<FindPetsByStatus400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? findPetsByStatusQueryKey(params);

  const query = useQuery(
    {
      ...findPetsByStatusQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<FindPetsByStatus400>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
