/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeletePetPathParams = {
  /**
   * @description Pet id to delete
   * @type integer, int64
   */
  petId: number;
};

export type DeletePetHeaderParams = {
  /**
   * @type string | undefined
   */
  api_key?: string;
};

/**
 * @description Pet deleted
 */
export type DeletePet200 = unknown;

/**
 * @description Invalid pet value
 */
export type DeletePet400 = unknown;

/**
 * @description Unexpected error
 */
export type DeletePetError = unknown;

export type DeletePetMutationResponse = DeletePet200;

export type DeletePetMutation = {
  Response: DeletePet200;
  PathParams: DeletePetPathParams;
  HeaderParams: DeletePetHeaderParams;
  Errors: DeletePet400;
};
