/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from '../Pet.ts';

export type UpdatePetWithFormPathParams = {
  /**
   * @description ID of pet that needs to be updated
   * @type integer, int64
   */
  petId: number;
};

export type UpdatePetWithFormQueryParams = {
  /**
   * @description Name of pet that needs to be updated
   * @type string | undefined
   */
  name?: string;
  /**
   * @description Status of pet that needs to be updated
   * @type string | undefined
   */
  status?: string;
};

/**
 * @description successful operation
 */
export type UpdatePetWithForm200 = Pet;

/**
 * @description Invalid input
 */
export type UpdatePetWithForm400 = unknown;

/**
 * @description Unexpected error
 */
export type UpdatePetWithFormError = unknown;

export type UpdatePetWithFormMutationResponse = UpdatePetWithForm200;

export type UpdatePetWithFormMutation = {
  Response: UpdatePetWithForm200;
  PathParams: UpdatePetWithFormPathParams;
  QueryParams: UpdatePetWithFormQueryParams;
  Errors: UpdatePetWithForm400;
};
