ls:
  src:
    .ts: camelCase
    .stories.ts: PascalCase
    .test.ts: PascalCase
    .tsx: PascalCase | regex:^(index|main|app|utils|const)$ | regex:^use(\w+)$
    .d.ts: camelCase | regex:^vite-env$
  src/components/ui:
    .stories.ts: camelCase
    .tsx: camelCase
  src/services:
    .ts: PascalCase | regex:^(http-client|data-contracts)$

ignore:
  - .git
  - node_modules
