packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  react-error-boundary: ^6.0.3
  antd: ^6.2.0
  tailwindcss: ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.1
  '@types/react': ^19.2.8
  '@types/react-dom': '^19.2.3'
  axios: ^1.13.2
  '@tanstack/react-query': ^5.90.16
  '@tanstack/react-router': ^1.147.3
  '@tanstack/react-router-devtools': ^1.149.0
  vite-plugin-svgr: ^4.5.0
  '@total-typescript/ts-reset': ^0.6.1
  '@vitejs/plugin-react': ^5.1.2
  msw: ^2.12.7
  rimraf: ^6.1.2
  zod: ^4.3.5
  '@biomejs/biome': ^2.3.11
  tsdown: ^0.19.0


