/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  CreateUsersWithListInputError,
  CreateUsersWithListInputMutationRequest,
  CreateUsersWithListInputMutationResponse,
} from '../../model/user/CreateUsersWithListInput.ts';
import { userSchema } from '../userSchema.ts';

/**
 * @description successful operation
 */
export const createUsersWithListInputErrorSchema =
  z.unknown() as unknown as z.ZodType<CreateUsersWithListInputError>;

/**
 * @description List of user object
 */
export const createUsersWithListInputMutationRequestSchema = z.array(
  z.lazy(() => userSchema),
) as unknown as z.ZodType<CreateUsersWithListInputMutationRequest>;

export const createUsersWithListInputMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<CreateUsersWithListInputMutationResponse>;
