/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  CreateUsersWithListInput200,
  CreateUsersWithListInputError,
  CreateUsersWithListInputMutationRequest,
  CreateUsersWithListInputMutationResponse,
} from '../../model/user/CreateUsersWithListInput.ts';
import { userSchema } from '../userSchema.ts';

/**
 * @description Successful operation
 */
export const createUsersWithListInput200Schema = z.lazy(
  () => userSchema,
) as unknown as z.ZodType<CreateUsersWithListInput200>;

/**
 * @description Unexpected error
 */
export const createUsersWithListInputErrorSchema =
  z.unknown() as unknown as z.ZodType<CreateUsersWithListInputError>;

export const createUsersWithListInputMutationRequestSchema = z.array(
  z.lazy(() => userSchema),
) as unknown as z.ZodType<CreateUsersWithListInputMutationRequest>;

export const createUsersWithListInputMutationResponseSchema = z.lazy(
  () => createUsersWithListInput200Schema,
) as unknown as z.ZodType<CreateUsersWithListInputMutationResponse>;
