/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  CreateUser200,
  CreateUserError,
  CreateUserMutationRequest,
  CreateUserMutationResponse,
} from '../../model/user/CreateUser.ts';
import { userSchema } from '../userSchema.ts';

/**
 * @description successful operation
 */
export const createUser200Schema = z.lazy(() => userSchema) as unknown as z.ZodType<CreateUser200>;

/**
 * @description Unexpected error
 */
export const createUserErrorSchema = z.unknown() as unknown as z.ZodType<CreateUserError>;

/**
 * @description Created user object
 */
export const createUserMutationRequestSchema = z.lazy(
  () => userSchema,
) as unknown as z.ZodType<CreateUserMutationRequest>;

export const createUserMutationResponseSchema = z.lazy(
  () => createUser200Schema,
) as unknown as z.ZodType<CreateUserMutationResponse>;
