/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  CreateUsersWithArrayInputError,
  CreateUsersWithArrayInputMutationRequest,
  CreateUsersWithArrayInputMutationResponse,
} from '../../model/user/CreateUsersWithArrayInput.ts';
import { userSchema } from '../userSchema.ts';

/**
 * @description successful operation
 */
export const createUsersWithArrayInputErrorSchema =
  z.unknown() as unknown as z.ZodType<CreateUsersWithArrayInputError>;

/**
 * @description List of user object
 */
export const createUsersWithArrayInputMutationRequestSchema = z.array(
  z.lazy(() => userSchema),
) as unknown as z.ZodType<CreateUsersWithArrayInputMutationRequest>;

export const createUsersWithArrayInputMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<CreateUsersWithArrayInputMutationResponse>;
