/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  DeleteUser400,
  DeleteUser404,
  DeleteUserMutationResponse,
  DeleteUserPathParams,
} from '../../model/user/DeleteUser.ts';

export const deleteUserPathParamsSchema = z.object({
  username: z.string().describe('The name that needs to be deleted'),
}) as unknown as z.ZodType<DeleteUserPathParams>;

/**
 * @description Invalid username supplied
 */
export const deleteUser400Schema = z.unknown() as unknown as z.ZodType<DeleteUser400>;

/**
 * @description User not found
 */
export const deleteUser404Schema = z.unknown() as unknown as z.ZodType<DeleteUser404>;

export const deleteUserMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<DeleteUserMutationResponse>;
