/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  GetUserByName200,
  GetUserByName400,
  GetUserByName404,
  GetUserByNamePathParams,
  GetUserByNameQueryResponse,
} from '../../model/user/GetUserByName.ts';
import { userSchema } from '../userSchema.ts';

export const getUserByNamePathParamsSchema = z.object({
  username: z.string().describe('The name that needs to be fetched. Use user1 for testing. '),
}) as unknown as z.ZodType<GetUserByNamePathParams>;

/**
 * @description successful operation
 */
export const getUserByName200Schema = z.lazy(
  () => userSchema,
) as unknown as z.ZodType<GetUserByName200>;

/**
 * @description Invalid username supplied
 */
export const getUserByName400Schema = z.unknown() as unknown as z.ZodType<GetUserByName400>;

/**
 * @description User not found
 */
export const getUserByName404Schema = z.unknown() as unknown as z.ZodType<GetUserByName404>;

export const getUserByNameQueryResponseSchema = z.lazy(
  () => getUserByName200Schema,
) as unknown as z.ZodType<GetUserByNameQueryResponse>;
