/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  LoginUser200,
  LoginUser400,
  LoginUserQueryParams,
  LoginUserQueryResponse,
} from '../../model/user/LoginUser.ts';

export const loginUserQueryParamsSchema = z.object({
  username: z.string().describe('The user name for login'),
  password: z.string().describe('The password for login in clear text'),
}) as unknown as z.ZodType<LoginUserQueryParams>;

/**
 * @description successful operation
 */
export const loginUser200Schema = z.string() as unknown as z.ZodType<LoginUser200>;

/**
 * @description Invalid username/password supplied
 */
export const loginUser400Schema = z.unknown() as unknown as z.ZodType<LoginUser400>;

export const loginUserQueryResponseSchema = z.lazy(
  () => loginUser200Schema,
) as unknown as z.ZodType<LoginUserQueryResponse>;
