/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type { LogoutUserError, LogoutUserQueryResponse } from '../../model/user/LogoutUser.ts';

/**
 * @description successful operation
 */
export const logoutUserErrorSchema = z.unknown() as unknown as z.ZodType<LogoutUserError>;

export const logoutUserQueryResponseSchema =
  z.unknown() as unknown as z.ZodType<LogoutUserQueryResponse>;
