/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  UpdateUser200,
  UpdateUser400,
  UpdateUser404,
  UpdateUserError,
  UpdateUserMutationRequest,
  UpdateUserMutationResponse,
  UpdateUserPathParams,
} from '../../model/user/UpdateUser.ts';
import { userSchema } from '../userSchema.ts';

export const updateUserPathParamsSchema = z.object({
  username: z.string().describe('name that need to be deleted'),
}) as unknown as z.ZodType<UpdateUserPathParams>;

/**
 * @description successful operation
 */
export const updateUser200Schema = z.unknown() as unknown as z.ZodType<UpdateUser200>;

/**
 * @description bad request
 */
export const updateUser400Schema = z.unknown() as unknown as z.ZodType<UpdateUser400>;

/**
 * @description user not found
 */
export const updateUser404Schema = z.unknown() as unknown as z.ZodType<UpdateUser404>;

/**
 * @description Unexpected error
 */
export const updateUserErrorSchema = z.unknown() as unknown as z.ZodType<UpdateUserError>;

/**
 * @description Update an existent user in the store
 */
export const updateUserMutationRequestSchema = z.lazy(
  () => userSchema,
) as unknown as z.ZodType<UpdateUserMutationRequest>;

export const updateUserMutationResponseSchema = z.lazy(
  () => updateUser200Schema,
) as unknown as z.ZodType<UpdateUserMutationResponse>;
