/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  UpdateUser400,
  UpdateUser404,
  UpdateUserMutationRequest,
  UpdateUserMutationResponse,
  UpdateUserPathParams,
} from '../../model/user/UpdateUser.ts';
import { userSchema } from '../userSchema.ts';

export const updateUserPathParamsSchema = z.object({
  username: z.string().describe('name that need to be updated'),
}) as unknown as z.ZodType<UpdateUserPathParams>;

/**
 * @description Invalid user supplied
 */
export const updateUser400Schema = z.unknown() as unknown as z.ZodType<UpdateUser400>;

/**
 * @description User not found
 */
export const updateUser404Schema = z.unknown() as unknown as z.ZodType<UpdateUser404>;

/**
 * @description Updated user object
 */
export const updateUserMutationRequestSchema = z.lazy(
  () => userSchema,
) as unknown as z.ZodType<UpdateUserMutationRequest>;

export const updateUserMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<UpdateUserMutationResponse>;
