/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/shared/lib/client';
import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import type {
  AddPet405,
  AddPetMutationRequest,
  AddPetMutationResponse,
} from '../../model/pet/AddPet.ts';

function getAddPetUrl() {
  const res = { method: 'POST', url: '/pet' as const };
  return res;
}

/**
 * @summary Add a new pet to the store
 * {@link /pet}
 */
export async function addPet(
  data: AddPetMutationRequest,
  config: Partial<RequestConfig<AddPetMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    AddPetMutationResponse,
    ResponseErrorConfig<AddPet405>,
    AddPetMutationRequest
  >({
    method: 'POST',
    url: getAddPetUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
