/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import fetch from '@/shared/lib/client';
import type {
  FindPetsByTags400,
  FindPetsByTagsQueryParams,
  FindPetsByTagsQueryResponse,
} from '../../model/pet/FindPetsByTags.ts';

function getFindPetsByTagsUrl() {
  const res = { method: 'GET', url: '/pet/findByTags' as const };
  return res;
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 * @deprecated
 */
export async function findPetsByTags(
  params: FindPetsByTagsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FindPetsByTagsQueryResponse,
    ResponseErrorConfig<FindPetsByTags400>,
    unknown
  >({
    method: 'GET',
    url: getFindPetsByTagsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
