/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import fetch from '@/shared/lib/client';
import type {
  UpdatePetWithForm405,
  UpdatePetWithFormMutationRequest,
  UpdatePetWithFormMutationResponse,
  UpdatePetWithFormPathParams,
} from '../../model/pet/UpdatePetWithForm.ts';

function getUpdatePetWithFormUrl({ petId }: { petId: UpdatePetWithFormPathParams['petId'] }) {
  const res = { method: 'POST', url: `/pet/${petId}` as const };
  return res;
}

/**
 * @summary Updates a pet in the store with form data
 * {@link /pet/:petId}
 */
export async function updatePetWithForm(
  { petId }: { petId: UpdatePetWithFormPathParams['petId'] },
  data?: UpdatePetWithFormMutationRequest,
  config: Partial<RequestConfig<UpdatePetWithFormMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    UpdatePetWithFormMutationResponse,
    ResponseErrorConfig<UpdatePetWithForm405>,
    UpdatePetWithFormMutationRequest
  >({
    method: 'POST',
    url: getUpdatePetWithFormUrl({ petId }).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...requestConfig.headers },
  });
  return res.data;
}
