/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createAddPetMutationResponse } from '../../faker/pet/createAddPet.ts';
import type { AddPet405, AddPetMutationResponse } from '../../model/pet/AddPet.ts';

export function addPetHandlerResponse405(data?: AddPet405) {
  return new Response(JSON.stringify(data), {
    status: 405,
  });
}

export function addPetHandler(
  data?:
    | AddPetMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/pet', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createAddPetMutationResponse(data)), {
      status: 200,
    });
  });
}
