/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createAddPetMutationResponse } from '../../faker/pet/createAddPet.ts';
import type { AddPet400, AddPet422, AddPetMutationResponse } from '../../model/pet/AddPet.ts';

export function addPetHandlerResponse200(data: AddPetMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function addPetHandlerResponse400(data?: AddPet400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function addPetHandlerResponse422(data?: AddPet422) {
  return new Response(JSON.stringify(data), {
    status: 422,
  });
}

export function addPetHandler(
  data?:
    | AddPetMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/pet', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createAddPetMutationResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
