/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createDeletePetMutationResponse } from '../../faker/pet/createDeletePet.ts';
import type { DeletePet400, DeletePetMutationResponse } from '../../model/pet/DeletePet.ts';

export function deletePetHandlerResponse200(data?: DeletePetMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
  });
}

export function deletePetHandlerResponse400(data?: DeletePet400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function deletePetHandler(
  data?:
    | DeletePetMutationResponse
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response | Promise<Response>),
) {
  return http.delete('/pet/:petId', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createDeletePetMutationResponse(data)), {
      status: 200,
    });
  });
}
