/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createFindPetsByStatusQueryResponse } from '../../faker/pet/createFindPetsByStatus.ts';
import type {
  FindPetsByStatus400,
  FindPetsByStatusQueryResponse,
} from '../../model/pet/FindPetsByStatus.ts';

export function findPetsByStatusHandlerResponse200(data: FindPetsByStatusQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function findPetsByStatusHandlerResponse400(data?: FindPetsByStatus400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function findPetsByStatusHandler(
  data?:
    | FindPetsByStatusQueryResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response | Promise<Response>),
) {
  return http.get('/pet/findByStatus', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createFindPetsByStatusQueryResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
