/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createFindPetsByTagsQueryResponse } from '../../faker/pet/createFindPetsByTags.ts';
import type {
  FindPetsByTags400,
  FindPetsByTagsQueryResponse,
} from '../../model/pet/FindPetsByTags.ts';

export function findPetsByTagsHandlerResponse200(data: FindPetsByTagsQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function findPetsByTagsHandlerResponse400(data?: FindPetsByTags400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function findPetsByTagsHandler(
  data?:
    | FindPetsByTagsQueryResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response | Promise<Response>),
) {
  return http.get('/pet/findByTags', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createFindPetsByTagsQueryResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
