/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createUpdatePetMutationResponse } from '../../faker/pet/createUpdatePet.ts';
import type {
  UpdatePet400,
  UpdatePet404,
  UpdatePet422,
  UpdatePetMutationResponse,
} from '../../model/pet/UpdatePet.ts';

export function updatePetHandlerResponse200(data: UpdatePetMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function updatePetHandlerResponse400(data?: UpdatePet400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function updatePetHandlerResponse404(data?: UpdatePet404) {
  return new Response(JSON.stringify(data), {
    status: 404,
  });
}

export function updatePetHandlerResponse422(data?: UpdatePet422) {
  return new Response(JSON.stringify(data), {
    status: 422,
  });
}

export function updatePetHandler(
  data?:
    | UpdatePetMutationResponse
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response | Promise<Response>),
) {
  return http.put('/pet', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createUpdatePetMutationResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
