/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createUpdatePetWithFormMutationResponse } from '../../faker/pet/createUpdatePetWithForm.ts';
import type {
  UpdatePetWithForm405,
  UpdatePetWithFormMutationResponse,
} from '../../model/pet/UpdatePetWithForm.ts';

export function updatePetWithFormHandlerResponse405(data?: UpdatePetWithForm405) {
  return new Response(JSON.stringify(data), {
    status: 405,
  });
}

export function updatePetWithFormHandler(
  data?:
    | UpdatePetWithFormMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/pet/:petId', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createUpdatePetWithFormMutationResponse(data)), {
      status: 200,
    });
  });
}
