/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createUploadFileMutationResponse } from '../../faker/pet/createUploadFile.ts';
import type { UploadFileMutationResponse } from '../../model/pet/UploadFile.ts';

export function uploadFileHandlerResponse200(data: UploadFileMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function uploadFileHandler(
  data?:
    | UploadFileMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/pet/:petId/uploadImage', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createUploadFileMutationResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
