/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { Order } from '../model/Order.ts';

export function createOrder(data?: Partial<Order>): Order {
  return {
    ...{
      id: faker.number.int(),
      petId: faker.number.int(),
      quantity: faker.number.int(),
      shipDate: faker.date.anytime(),
      status: faker.helpers.arrayElement<NonNullable<Order>['status']>([
        'placed',
        'approved',
        'delivered',
      ]),
      complete: faker.datatype.boolean(),
    },
    ...(data || {}),
  };
}
