/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { Pet } from '../model/Pet.ts';
import { createCategory } from './createCategory.ts';
import { createTag } from './createTag.ts';

export function createPet(data?: Partial<Pet>): Pet {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int(),
      name: faker.string.alpha(),
      category: createCategory(),
      photoUrls: faker.helpers.multiple(() => faker.string.alpha()),
      tags: faker.helpers.multiple(() => createTag()),
      status: faker.helpers.arrayElement<NonNullable<Pet>['status']>([
        'available',
        'pending',
        'sold',
      ]),
    },
    ...(data || {}),
  };
}
