/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from '../User.ts';

/**
 * @description successful operation
 */
export type CreateUser200 = User;

/**
 * @description Unexpected error
 */
export type CreateUserError = unknown;

/**
 * @description Created user object
 */
export type CreateUserMutationRequest = User;

export type CreateUserMutationResponse = CreateUser200;

export type CreateUserMutation = {
  Response: CreateUser200;
  Request: CreateUserMutationRequest;
  Errors: any;
};
