/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteUserPathParams = {
  /**
   * @description The name that needs to be deleted
   * @type string
   */
  username: string;
};

/**
 * @description User deleted
 */
export type DeleteUser200 = unknown;

/**
 * @description Invalid username supplied
 */
export type DeleteUser400 = unknown;

/**
 * @description User not found
 */
export type DeleteUser404 = unknown;

/**
 * @description Unexpected error
 */
export type DeleteUserError = unknown;

export type DeleteUserMutationResponse = DeleteUser200;

export type DeleteUserMutation = {
  Response: DeleteUser200;
  PathParams: DeleteUserPathParams;
  Errors: DeleteUser400 | DeleteUser404;
};
