/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description successful operation
 */
export type LogoutUser200 = unknown;

/**
 * @description Unexpected error
 */
export type LogoutUserError = unknown;

export type LogoutUserQueryResponse = LogoutUser200;

export type LogoutUserQuery = {
  Response: LogoutUser200;
  Errors: any;
};
