/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from '../User.ts';

export type UpdateUserPathParams = {
  /**
   * @description name that need to be deleted
   * @type string
   */
  username: string;
};

/**
 * @description successful operation
 */
export type UpdateUser200 = unknown;

/**
 * @description bad request
 */
export type UpdateUser400 = unknown;

/**
 * @description user not found
 */
export type UpdateUser404 = unknown;

/**
 * @description Unexpected error
 */
export type UpdateUserError = unknown;

/**
 * @description Update an existent user in the store
 */
export type UpdateUserMutationRequest = User;

export type UpdateUserMutationResponse = UpdateUser200;

export type UpdateUserMutation = {
  Response: UpdateUser200;
  Request: UpdateUserMutationRequest;
  PathParams: UpdateUserPathParams;
  Errors: UpdateUser400 | UpdateUser404;
};
