/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { CreateUserMutationResponse } from '../../model/user/CreateUser.ts';
import { createUser } from '../createUser.ts';

/**
 * @description successful operation
 */
export function createCreateUserError() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Created user object
 */
export function createCreateUserMutationRequest() {
  faker.seed([100]);
  return createUser();
}

export function createCreateUserMutationResponse(
  _data?: Partial<CreateUserMutationResponse>,
): CreateUserMutationResponse {
  faker.seed([100]);
  return undefined;
}
