/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { LogoutUserQueryResponse } from '../../model/user/LogoutUser.ts';

/**
 * @description successful operation
 */
export function createLogoutUserError() {
  faker.seed([100]);
  return undefined;
}

export function createLogoutUserQueryResponse(
  _data?: Partial<LogoutUserQueryResponse>,
): LogoutUserQueryResponse {
  faker.seed([100]);
  return undefined;
}
