/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  UpdateUserMutationResponse,
  UpdateUserPathParams,
} from '../../model/user/UpdateUser.ts';
import { createUser } from '../createUser.ts';

export function createUpdateUserPathParams(
  data?: Partial<UpdateUserPathParams>,
): UpdateUserPathParams {
  return {
    ...{ username: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createUpdateUser200() {
  return undefined;
}

/**
 * @description bad request
 */
export function createUpdateUser400() {
  return undefined;
}

/**
 * @description user not found
 */
export function createUpdateUser404() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createUpdateUserError() {
  return undefined;
}

/**
 * @description Update an existent user in the store
 */
export function createUpdateUserMutationRequest() {
  return createUser();
}

export function createUpdateUserMutationResponse(
  data?: Partial<UpdateUserMutationResponse>,
): UpdateUserMutationResponse {
  return data || faker.helpers.arrayElement<any>([createUpdateUser200()]);
}
