/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  UpdateUserMutationResponse,
  UpdateUserPathParams,
} from '../../model/user/UpdateUser.ts';
import { createUser } from '../createUser.ts';

export function createUpdateUserPathParams(
  data?: Partial<UpdateUserPathParams>,
): UpdateUserPathParams {
  faker.seed([100]);
  return {
    ...{ username: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Invalid user supplied
 */
export function createUpdateUser400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description User not found
 */
export function createUpdateUser404() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Updated user object
 */
export function createUpdateUserMutationRequest() {
  faker.seed([100]);
  return createUser();
}

export function createUpdateUserMutationResponse(
  _data?: Partial<UpdateUserMutationResponse>,
): UpdateUserMutationResponse {
  faker.seed([100]);
  return undefined;
}
