/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  CreateUsersWithListInputMutationRequest,
  CreateUsersWithListInputMutationResponse,
} from '../../model/user/CreateUsersWithListInput.ts';
import { createUser } from '../createUser.ts';

/**
 * @description Successful operation
 */
export function createCreateUsersWithListInput200() {
  faker.seed([100]);
  return createUser();
}

/**
 * @description Unexpected error
 */
export function createCreateUsersWithListInputError() {
  faker.seed([100]);
  return undefined;
}

export function createCreateUsersWithListInputMutationRequest(
  data?: CreateUsersWithListInputMutationRequest,
): CreateUsersWithListInputMutationRequest {
  faker.seed([100]);
  return [...faker.helpers.multiple(() => createUser()), ...(data || [])];
}

export function createCreateUsersWithListInputMutationResponse(
  data?: Partial<CreateUsersWithListInputMutationResponse>,
): CreateUsersWithListInputMutationResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createCreateUsersWithListInput200()]);
}
