/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { CreateUserMutationResponse } from '../../model/user/CreateUser.ts';
import { createUser } from '../createUser.ts';

/**
 * @description successful operation
 */
export function createCreateUser200() {
  return createUser();
}

/**
 * @description Unexpected error
 */
export function createCreateUserError() {
  return undefined;
}

/**
 * @description Created user object
 */
export function createCreateUserMutationRequest() {
  return createUser();
}

export function createCreateUserMutationResponse(
  data?: Partial<CreateUserMutationResponse>,
): CreateUserMutationResponse {
  return data || faker.helpers.arrayElement<any>([createCreateUser200()]);
}
