/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  DeleteUserMutationResponse,
  DeleteUserPathParams,
} from '../../model/user/DeleteUser.ts';

export function createDeleteUserPathParams(
  data?: Partial<DeleteUserPathParams>,
): DeleteUserPathParams {
  faker.seed([100]);
  return {
    ...{ username: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description User deleted
 */
export function createDeleteUser200() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Invalid username supplied
 */
export function createDeleteUser400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description User not found
 */
export function createDeleteUser404() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createDeleteUserError() {
  faker.seed([100]);
  return undefined;
}

export function createDeleteUserMutationResponse(
  data?: Partial<DeleteUserMutationResponse>,
): DeleteUserMutationResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createDeleteUser200()]);
}
