/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { LoginUserQueryParams, LoginUserQueryResponse } from '../../model/user/LoginUser.ts';

export function createLoginUserQueryParams(
  data?: Partial<LoginUserQueryParams>,
): LoginUserQueryParams {
  return {
    ...{ username: faker.string.alpha(), password: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createLoginUser200() {
  return faker.string.alpha();
}

/**
 * @description Invalid username/password supplied
 */
export function createLoginUser400() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createLoginUserError() {
  return undefined;
}

export function createLoginUserQueryResponse(
  data?: Partial<LoginUserQueryResponse>,
): LoginUserQueryResponse {
  return data || faker.helpers.arrayElement<any>([createLoginUser200()]);
}
