/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  GetUserByNamePathParams,
  GetUserByNameQueryResponse,
} from '../../model/user/GetUserByName.ts';
import { createUser } from '../createUser.ts';

export function createGetUserByNamePathParams(
  data?: Partial<GetUserByNamePathParams>,
): GetUserByNamePathParams {
  return {
    ...{ username: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createGetUserByName200() {
  return createUser();
}

/**
 * @description Invalid username supplied
 */
export function createGetUserByName400() {
  return undefined;
}

/**
 * @description User not found
 */
export function createGetUserByName404() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createGetUserByNameError() {
  return undefined;
}

export function createGetUserByNameQueryResponse(
  data?: Partial<GetUserByNameQueryResponse>,
): GetUserByNameQueryResponse {
  return data || faker.helpers.arrayElement<any>([createGetUserByName200()]);
}
