/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  CreateUsersWithArrayInputMutationRequest,
  CreateUsersWithArrayInputMutationResponse,
} from '../../model/user/CreateUsersWithArrayInput.ts';
import { createUser } from '../createUser.ts';

/**
 * @description successful operation
 */
export function createCreateUsersWithArrayInputError() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description List of user object
 */
export function createCreateUsersWithArrayInputMutationRequest(
  data?: CreateUsersWithArrayInputMutationRequest,
): CreateUsersWithArrayInputMutationRequest {
  faker.seed([100]);
  return [...faker.helpers.multiple(() => createUser()), ...(data || [])];
}

export function createCreateUsersWithArrayInputMutationResponse(
  _data?: Partial<CreateUsersWithArrayInputMutationResponse>,
): CreateUsersWithArrayInputMutationResponse {
  faker.seed([100]);
  return undefined;
}
