/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@repo/lib/client';
import fetch from '@repo/lib/client';
import type {
  CreateUserMutationRequest,
  CreateUserMutationResponse,
} from '../../model/user/CreateUser.ts';

export function getCreateUserUrl() {
  const res = { method: 'POST', url: `/user` as const };
  return res;
}

/**
 * @description This can only be done by the logged in user.
 * @summary Create user.
 * {@link /user}
 */
export async function createUser(
  data?: CreateUserMutationRequest,
  config: Partial<RequestConfig<CreateUserMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateUserMutationResponse,
    ResponseErrorConfig<Error>,
    CreateUserMutationRequest
  >({
    method: 'POST',
    url: getCreateUserUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
