/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@repo/lib/client';
import fetch from '@repo/lib/client';
import type {
  CreateUsersWithArrayInputMutationRequest,
  CreateUsersWithArrayInputMutationResponse,
} from '../../model/user/CreateUsersWithArrayInput.ts';

export function getCreateUsersWithArrayInputUrl() {
  const res = { method: 'POST', url: `/user/createWithArray` as const };
  return res;
}

/**
 * @summary Creates list of users with given input array
 * {@link /user/createWithArray}
 */
export async function createUsersWithArrayInput(
  data?: CreateUsersWithArrayInputMutationRequest,
  config: Partial<RequestConfig<CreateUsersWithArrayInputMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateUsersWithArrayInputMutationResponse,
    ResponseErrorConfig<Error>,
    CreateUsersWithArrayInputMutationRequest
  >({
    method: 'POST',
    url: getCreateUsersWithArrayInputUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
