/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@repo/lib/client';
import fetch from '@repo/lib/client';
import type {
  GetUserByName400,
  GetUserByName404,
  GetUserByNamePathParams,
  GetUserByNameQueryResponse,
} from '../../model/user/GetUserByName.ts';

export function getGetUserByNameUrl({
  username,
}: {
  username: GetUserByNamePathParams['username'];
}) {
  const res = { method: 'GET', url: `/user/${username}` as const };
  return res;
}

/**
 * @description Get user detail based on username.
 * @summary Get user by user name.
 * {@link /user/:username}
 */
export async function getUserByName(
  { username }: { username: GetUserByNamePathParams['username'] },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserByNameQueryResponse,
    ResponseErrorConfig<GetUserByName400 | GetUserByName404>,
    unknown
  >({ method: 'GET', url: getGetUserByNameUrl({ username }).url.toString(), ...requestConfig });
  return res.data;
}
