/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { UpdatePetMutationResponse } from '../../model/pet/UpdatePet.ts';
import { createPet } from '../createPet.ts';

/**
 * @description Successful operation
 */
export function createUpdatePet200() {
  faker.seed([100]);
  return createPet();
}

/**
 * @description Invalid ID supplied
 */
export function createUpdatePet400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet not found
 */
export function createUpdatePet404() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Validation exception
 */
export function createUpdatePet422() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createUpdatePetError() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Update an existent pet in the store
 */
export function createUpdatePetMutationRequest() {
  faker.seed([100]);
  return createPet();
}

export function createUpdatePetMutationResponse(
  data?: Partial<UpdatePetMutationResponse>,
): UpdatePetMutationResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createUpdatePet200()]);
}
