/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  UpdatePetWithFormMutationRequest,
  UpdatePetWithFormMutationResponse,
  UpdatePetWithFormPathParams,
} from '../../model/pet/UpdatePetWithForm.ts';

export function createUpdatePetWithFormPathParams(
  data?: Partial<UpdatePetWithFormPathParams>,
): UpdatePetWithFormPathParams {
  faker.seed([100]);
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

/**
 * @description Invalid input
 */
export function createUpdatePetWithForm405() {
  faker.seed([100]);
  return undefined;
}

export function createUpdatePetWithFormMutationRequest(
  data?: Partial<UpdatePetWithFormMutationRequest>,
): UpdatePetWithFormMutationRequest {
  faker.seed([100]);
  return {
    ...{ name: faker.string.alpha(), status: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createUpdatePetWithFormMutationResponse(
  _data?: Partial<UpdatePetWithFormMutationResponse>,
): UpdatePetWithFormMutationResponse {
  faker.seed([100]);
  return undefined;
}
