/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  DeletePetHeaderParams,
  DeletePetMutationResponse,
  DeletePetPathParams,
} from '../../model/pet/DeletePet.ts';

export function createDeletePetPathParams(
  data?: Partial<DeletePetPathParams>,
): DeletePetPathParams {
  faker.seed([100]);
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

export function createDeletePetHeaderParams(
  data?: Partial<DeletePetHeaderParams>,
): DeletePetHeaderParams {
  faker.seed([100]);
  return {
    ...{ api_key: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Invalid ID supplied
 */
export function createDeletePet400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet not found
 */
export function createDeletePet404() {
  faker.seed([100]);
  return undefined;
}

export function createDeletePetMutationResponse(
  _data?: Partial<DeletePetMutationResponse>,
): DeletePetMutationResponse {
  faker.seed([100]);
  return undefined;
}
