/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { AddPetMutationResponse } from '../../model/pet/AddPet.ts';
import { createPet } from '../createPet.ts';

/**
 * @description Invalid input
 */
export function createAddPet405() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet object that needs to be added to the store
 */
export function createAddPetMutationRequest() {
  faker.seed([100]);
  return createPet();
}

export function createAddPetMutationResponse(
  _data?: Partial<AddPetMutationResponse>,
): AddPetMutationResponse {
  faker.seed([100]);
  return undefined;
}
