/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  FindPetsByTags200,
  FindPetsByTagsQueryParams,
  FindPetsByTagsQueryResponse,
} from '../../model/pet/FindPetsByTags.ts';
import { createPet } from '../createPet.ts';

export function createFindPetsByTagsQueryParams(
  data?: Partial<FindPetsByTagsQueryParams>,
): FindPetsByTagsQueryParams {
  return {
    ...{ tags: faker.helpers.multiple(() => faker.string.alpha()) },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createFindPetsByTags200(data?: FindPetsByTags200): FindPetsByTags200 {
  return [...faker.helpers.multiple(() => createPet()), ...(data || [])];
}

/**
 * @description Invalid tag value
 */
export function createFindPetsByTags400() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createFindPetsByTagsError() {
  return undefined;
}

export function createFindPetsByTagsQueryResponse(
  data?: Partial<FindPetsByTagsQueryResponse>,
): FindPetsByTagsQueryResponse {
  return data || faker.helpers.arrayElement<any>([createFindPetsByTags200()]);
}
