/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { AddPetMutationResponse } from '../../model/pet/AddPet.ts';
import { createPet } from '../createPet.ts';

/**
 * @description Successful operation
 */
export function createAddPet200() {
  return createPet();
}

/**
 * @description Invalid input
 */
export function createAddPet400() {
  return undefined;
}

/**
 * @description Validation exception
 */
export function createAddPet422() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createAddPetError() {
  return undefined;
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetMutationRequest() {
  return createPet();
}

export function createAddPetMutationResponse(
  data?: Partial<AddPetMutationResponse>,
): AddPetMutationResponse {
  return data || faker.helpers.arrayElement<any>([createAddPet200()]);
}
