/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  DeletePetHeaderParams,
  DeletePetMutationResponse,
  DeletePetPathParams,
} from '../../model/pet/DeletePet.ts';

export function createDeletePetPathParams(
  data?: Partial<DeletePetPathParams>,
): DeletePetPathParams {
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

export function createDeletePetHeaderParams(
  data?: Partial<DeletePetHeaderParams>,
): DeletePetHeaderParams {
  return {
    ...{ api_key: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Pet deleted
 */
export function createDeletePet200() {
  return undefined;
}

/**
 * @description Invalid pet value
 */
export function createDeletePet400() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createDeletePetError() {
  return undefined;
}

export function createDeletePetMutationResponse(
  data?: Partial<DeletePetMutationResponse>,
): DeletePetMutationResponse {
  return data || faker.helpers.arrayElement<any>([createDeletePet200()]);
}
