/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  UpdatePetWithFormMutationResponse,
  UpdatePetWithFormPathParams,
  UpdatePetWithFormQueryParams,
} from '../../model/pet/UpdatePetWithForm.ts';
import { createPet } from '../createPet.ts';

export function createUpdatePetWithFormPathParams(
  data?: Partial<UpdatePetWithFormPathParams>,
): UpdatePetWithFormPathParams {
  faker.seed([100]);
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

export function createUpdatePetWithFormQueryParams(
  data?: Partial<UpdatePetWithFormQueryParams>,
): UpdatePetWithFormQueryParams {
  faker.seed([100]);
  return {
    ...{ name: faker.string.alpha(), status: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createUpdatePetWithForm200() {
  faker.seed([100]);
  return createPet();
}

/**
 * @description Invalid input
 */
export function createUpdatePetWithForm400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createUpdatePetWithFormError() {
  faker.seed([100]);
  return undefined;
}

export function createUpdatePetWithFormMutationResponse(
  data?: Partial<UpdatePetWithFormMutationResponse>,
): UpdatePetWithFormMutationResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createUpdatePetWithForm200()]);
}
