/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { UpdatePetMutationResponse } from '../../model/pet/UpdatePet.ts';
import { createPet } from '../createPet.ts';

/**
 * @description Invalid ID supplied
 */
export function createUpdatePet400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet not found
 */
export function createUpdatePet404() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Validation exception
 */
export function createUpdatePet405() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet object that needs to be added to the store
 */
export function createUpdatePetMutationRequest() {
  faker.seed([100]);
  return createPet();
}

export function createUpdatePetMutationResponse(
  _data?: Partial<UpdatePetMutationResponse>,
): UpdatePetMutationResponse {
  faker.seed([100]);
  return undefined;
}
