/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  UploadFileMutationRequest,
  UploadFileMutationResponse,
  UploadFilePathParams,
} from '../../model/pet/UploadFile.ts';
import { createApiResponse } from '../createApiResponse.ts';

export function createUploadFilePathParams(
  data?: Partial<UploadFilePathParams>,
): UploadFilePathParams {
  faker.seed([100]);
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createUploadFile200() {
  faker.seed([100]);
  return createApiResponse();
}

export function createUploadFileMutationRequest(
  data?: Partial<UploadFileMutationRequest>,
): UploadFileMutationRequest {
  faker.seed([100]);
  return {
    ...{ additionalMetadata: faker.string.alpha(), file: faker.image.url() as unknown as Blob },
    ...(data || {}),
  };
}

export function createUploadFileMutationResponse(
  data?: Partial<UploadFileMutationResponse>,
): UploadFileMutationResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createUploadFile200()]);
}
