/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { GetPetByIdPathParams, GetPetByIdQueryResponse } from '../../model/pet/GetPetById.ts';
import { createPet } from '../createPet.ts';

export function createGetPetByIdPathParams(
  data?: Partial<GetPetByIdPathParams>,
): GetPetByIdPathParams {
  faker.seed([100]);
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createGetPetById200() {
  faker.seed([100]);
  return createPet();
}

/**
 * @description Invalid ID supplied
 */
export function createGetPetById400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet not found
 */
export function createGetPetById404() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createGetPetByIdError() {
  faker.seed([100]);
  return undefined;
}

export function createGetPetByIdQueryResponse(
  data?: Partial<GetPetByIdQueryResponse>,
): GetPetByIdQueryResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createGetPetById200()]);
}
