/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  UploadFileMutationResponse,
  UploadFilePathParams,
  UploadFileQueryParams,
} from '../../model/pet/UploadFile.ts';
import { createApiResponse } from '../createApiResponse.ts';

export function createUploadFilePathParams(
  data?: Partial<UploadFilePathParams>,
): UploadFilePathParams {
  faker.seed([100]);
  return {
    ...{ petId: faker.number.int() },
    ...(data || {}),
  };
}

export function createUploadFileQueryParams(
  data?: Partial<UploadFileQueryParams>,
): UploadFileQueryParams {
  faker.seed([100]);
  return {
    ...{ additionalMetadata: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description successful operation
 */
export function createUploadFile200() {
  faker.seed([100]);
  return createApiResponse();
}

/**
 * @description No file uploaded
 */
export function createUploadFile400() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Pet not found
 */
export function createUploadFile404() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createUploadFileError() {
  faker.seed([100]);
  return undefined;
}

export function createUploadFileMutationRequest() {
  faker.seed([100]);
  return faker.image.url() as unknown as Blob;
}

export function createUploadFileMutationResponse(
  data?: Partial<UploadFileMutationResponse>,
): UploadFileMutationResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createUploadFile200()]);
}
