/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  AddPet405,
  AddPetMutationRequest,
  AddPetMutationResponse,
} from '../../model/pet/AddPet.ts';
import { petSchema } from '../petSchema.ts';

/**
 * @description Invalid input
 */
export const addPet405Schema = z.unknown() as unknown as z.ZodType<AddPet405>;

/**
 * @description Pet object that needs to be added to the store
 */
export const addPetMutationRequestSchema = z.lazy(
  () => petSchema,
) as unknown as z.ZodType<AddPetMutationRequest>;

export const addPetMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<AddPetMutationResponse>;
