/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  DeletePet400,
  DeletePet404,
  DeletePetHeaderParams,
  DeletePetMutationResponse,
  DeletePetPathParams,
} from '../../model/pet/DeletePet.ts';

export const deletePetPathParamsSchema = z.object({
  petId: z.coerce.number().int().describe('Pet id to delete'),
}) as unknown as z.ZodType<DeletePetPathParams>;

export const deletePetHeaderParamsSchema = z
  .object({
    api_key: z.optional(z.string()),
  })
  .optional() as unknown as z.ZodType<DeletePetHeaderParams>;

/**
 * @description Invalid ID supplied
 */
export const deletePet400Schema = z.unknown() as unknown as z.ZodType<DeletePet400>;

/**
 * @description Pet not found
 */
export const deletePet404Schema = z.unknown() as unknown as z.ZodType<DeletePet404>;

export const deletePetMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<DeletePetMutationResponse>;
