/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  DeletePet200,
  DeletePet400,
  DeletePetError,
  DeletePetHeaderParams,
  DeletePetMutationResponse,
  DeletePetPathParams,
} from '../../model/pet/DeletePet.ts';

export const deletePetPathParamsSchema = z.object({
  petId: z.coerce.number().int().describe('Pet id to delete'),
}) as unknown as z.ZodType<DeletePetPathParams>;

export const deletePetHeaderParamsSchema = z
  .object({
    api_key: z.optional(z.string()),
  })
  .optional() as unknown as z.ZodType<DeletePetHeaderParams>;

/**
 * @description Pet deleted
 */
export const deletePet200Schema = z.unknown() as unknown as z.ZodType<DeletePet200>;

/**
 * @description Invalid pet value
 */
export const deletePet400Schema = z.unknown() as unknown as z.ZodType<DeletePet400>;

/**
 * @description Unexpected error
 */
export const deletePetErrorSchema = z.unknown() as unknown as z.ZodType<DeletePetError>;

export const deletePetMutationResponseSchema = z.lazy(
  () => deletePet200Schema,
) as unknown as z.ZodType<DeletePetMutationResponse>;
