/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  FindPetsByTags200,
  FindPetsByTags400,
  FindPetsByTagsError,
  FindPetsByTagsQueryParams,
  FindPetsByTagsQueryResponse,
} from '../../model/pet/FindPetsByTags.ts';
import { petSchema } from '../petSchema.ts';

export const findPetsByTagsQueryParamsSchema = z.object({
  tags: z.array(z.string()).describe('Tags to filter by'),
}) as unknown as z.ZodType<FindPetsByTagsQueryParams>;

/**
 * @description successful operation
 */
export const findPetsByTags200Schema = z.array(
  z.lazy(() => petSchema),
) as unknown as z.ZodType<FindPetsByTags200>;

/**
 * @description Invalid tag value
 */
export const findPetsByTags400Schema = z.unknown() as unknown as z.ZodType<FindPetsByTags400>;

/**
 * @description Unexpected error
 */
export const findPetsByTagsErrorSchema = z.unknown() as unknown as z.ZodType<FindPetsByTagsError>;

export const findPetsByTagsQueryResponseSchema = z.lazy(
  () => findPetsByTags200Schema,
) as unknown as z.ZodType<FindPetsByTagsQueryResponse>;
