/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  FindPetsByStatus200,
  FindPetsByStatus400,
  FindPetsByStatusQueryParams,
  FindPetsByStatusQueryResponse,
} from '../../model/pet/FindPetsByStatus.ts';
import { petSchema } from '../petSchema.ts';

export const findPetsByStatusQueryParamsSchema = z.object({
  status: z
    .array(z.enum(['available', 'pending', 'sold']).default('available'))
    .describe('Status values that need to be considered for filter'),
}) as unknown as z.ZodType<FindPetsByStatusQueryParams>;

/**
 * @description successful operation
 */
export const findPetsByStatus200Schema = z.array(
  z.lazy(() => petSchema),
) as unknown as z.ZodType<FindPetsByStatus200>;

/**
 * @description Invalid status value
 */
export const findPetsByStatus400Schema = z.unknown() as unknown as z.ZodType<FindPetsByStatus400>;

export const findPetsByStatusQueryResponseSchema = z.lazy(
  () => findPetsByStatus200Schema,
) as unknown as z.ZodType<FindPetsByStatusQueryResponse>;
