/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  GetPetById200,
  GetPetById400,
  GetPetById404,
  GetPetByIdPathParams,
  GetPetByIdQueryResponse,
} from '../../model/pet/GetPetById.ts';
import { petSchema } from '../petSchema.ts';

export const getPetByIdPathParamsSchema = z.object({
  petId: z.coerce.number().int().describe('ID of pet to return'),
}) as unknown as z.ZodType<GetPetByIdPathParams>;

/**
 * @description successful operation
 */
export const getPetById200Schema = z.lazy(() => petSchema) as unknown as z.ZodType<GetPetById200>;

/**
 * @description Invalid ID supplied
 */
export const getPetById400Schema = z.unknown() as unknown as z.ZodType<GetPetById400>;

/**
 * @description Pet not found
 */
export const getPetById404Schema = z.unknown() as unknown as z.ZodType<GetPetById404>;

export const getPetByIdQueryResponseSchema = z.lazy(
  () => getPetById200Schema,
) as unknown as z.ZodType<GetPetByIdQueryResponse>;
