/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  UpdatePet400,
  UpdatePet404,
  UpdatePet405,
  UpdatePetMutationRequest,
  UpdatePetMutationResponse,
} from '../../model/pet/UpdatePet.ts';
import { petSchema } from '../petSchema.ts';

/**
 * @description Invalid ID supplied
 */
export const updatePet400Schema = z.unknown() as unknown as z.ZodType<UpdatePet400>;

/**
 * @description Pet not found
 */
export const updatePet404Schema = z.unknown() as unknown as z.ZodType<UpdatePet404>;

/**
 * @description Validation exception
 */
export const updatePet405Schema = z.unknown() as unknown as z.ZodType<UpdatePet405>;

/**
 * @description Pet object that needs to be added to the store
 */
export const updatePetMutationRequestSchema = z.lazy(
  () => petSchema,
) as unknown as z.ZodType<UpdatePetMutationRequest>;

export const updatePetMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<UpdatePetMutationResponse>;
