/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  UpdatePet200,
  UpdatePet400,
  UpdatePet404,
  UpdatePet422,
  UpdatePetError,
  UpdatePetMutationRequest,
  UpdatePetMutationResponse,
} from '../../model/pet/UpdatePet.ts';
import { petSchema } from '../petSchema.ts';

/**
 * @description Successful operation
 */
export const updatePet200Schema = z.lazy(() => petSchema) as unknown as z.ZodType<UpdatePet200>;

/**
 * @description Invalid ID supplied
 */
export const updatePet400Schema = z.unknown() as unknown as z.ZodType<UpdatePet400>;

/**
 * @description Pet not found
 */
export const updatePet404Schema = z.unknown() as unknown as z.ZodType<UpdatePet404>;

/**
 * @description Validation exception
 */
export const updatePet422Schema = z.unknown() as unknown as z.ZodType<UpdatePet422>;

/**
 * @description Unexpected error
 */
export const updatePetErrorSchema = z.unknown() as unknown as z.ZodType<UpdatePetError>;

/**
 * @description Update an existent pet in the store
 */
export const updatePetMutationRequestSchema = z.lazy(
  () => petSchema,
) as unknown as z.ZodType<UpdatePetMutationRequest>;

export const updatePetMutationResponseSchema = z.lazy(
  () => updatePet200Schema,
) as unknown as z.ZodType<UpdatePetMutationResponse>;
