/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  UpdatePetWithForm405,
  UpdatePetWithFormMutationRequest,
  UpdatePetWithFormMutationResponse,
  UpdatePetWithFormPathParams,
} from '../../model/pet/UpdatePetWithForm.ts';

export const updatePetWithFormPathParamsSchema = z.object({
  petId: z.coerce.number().int().describe('ID of pet that needs to be updated'),
}) as unknown as z.ZodType<UpdatePetWithFormPathParams>;

/**
 * @description Invalid input
 */
export const updatePetWithForm405Schema = z.unknown() as unknown as z.ZodType<UpdatePetWithForm405>;

export const updatePetWithFormMutationRequestSchema = z.object({
  name: z.optional(z.string().describe('Updated name of the pet')),
  status: z.optional(z.string().describe('Updated status of the pet')),
}) as unknown as z.ZodType<UpdatePetWithFormMutationRequest>;

export const updatePetWithFormMutationResponseSchema =
  z.unknown() as unknown as z.ZodType<UpdatePetWithFormMutationResponse>;
