/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  UploadFile200,
  UploadFileMutationRequest,
  UploadFileMutationResponse,
  UploadFilePathParams,
} from '../../model/pet/UploadFile.ts';
import { apiResponseSchema } from '../apiResponseSchema.ts';

export const uploadFilePathParamsSchema = z.object({
  petId: z.coerce.number().int().describe('ID of pet to update'),
}) as unknown as z.ZodType<UploadFilePathParams>;

/**
 * @description successful operation
 */
export const uploadFile200Schema = z.lazy(
  () => apiResponseSchema,
) as unknown as z.ZodType<UploadFile200>;

export const uploadFileMutationRequestSchema = z.object({
  additionalMetadata: z.optional(z.string().describe('Additional data to pass to server')),
  file: z.optional(z.instanceof(File).describe('file to upload')),
}) as unknown as z.ZodType<UploadFileMutationRequest>;

export const uploadFileMutationResponseSchema = z.lazy(
  () => uploadFile200Schema,
) as unknown as z.ZodType<UploadFileMutationResponse>;
