/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import fetch from '@/shared/lib/client';
import type {
  UpdateUser400,
  UpdateUser404,
  UpdateUserMutationRequest,
  UpdateUserMutationResponse,
  UpdateUserPathParams,
} from '../../model/user/UpdateUser.ts';

function getUpdateUserUrl({ username }: { username: UpdateUserPathParams['username'] }) {
  const res = { method: 'PUT', url: `/user/${username}` as const };
  return res;
}

/**
 * @description This can only be done by the logged in user.
 * @summary Updated user
 * {@link /user/:username}
 */
export async function updateUser(
  { username }: { username: UpdateUserPathParams['username'] },
  data?: UpdateUserMutationRequest,
  config: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    UpdateUserMutationResponse,
    ResponseErrorConfig<UpdateUser400 | UpdateUser404>,
    UpdateUserMutationRequest
  >({
    method: 'PUT',
    url: getUpdateUserUrl({ username }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
