/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/shared/lib/client';
import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import type {
  DeleteOrder400,
  DeleteOrder404,
  DeleteOrderMutationResponse,
  DeleteOrderPathParams,
} from '../../model/store/DeleteOrder.ts';

function getDeleteOrderUrl({ orderId }: { orderId: DeleteOrderPathParams['orderId'] }) {
  const res = { method: 'DELETE', url: `/store/order/${orderId}` as const };
  return res;
}

/**
 * @description For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
 * @summary Delete purchase order by ID
 * {@link /store/order/:orderId}
 */
export async function deleteOrder(
  { orderId }: { orderId: DeleteOrderPathParams['orderId'] },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteOrderMutationResponse,
    ResponseErrorConfig<DeleteOrder400 | DeleteOrder404>,
    unknown
  >({
    method: 'DELETE',
    url: getDeleteOrderUrl({ orderId }).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
