/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import fetch from '@/shared/lib/client';
import type { GetInventoryQueryResponse } from '../../model/store/GetInventory.ts';

function getGetInventoryUrl() {
  const res = { method: 'GET', url: '/store/inventory' as const };
  return res;
}

/**
 * @description Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 * {@link /store/inventory}
 */
export async function getInventory(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<GetInventoryQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getGetInventoryUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
