/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/shared/lib/client';
import fetch from '@/shared/lib/client';
import type {
  PlaceOrder400,
  PlaceOrderMutationRequest,
  PlaceOrderMutationResponse,
} from '../../model/store/PlaceOrder.ts';

export function getPlaceOrderUrl() {
  const res = { method: 'POST', url: `/store/order` as const };
  return res;
}

/**
 * @summary Place an order for a pet
 * {@link /store/order}
 */
export async function placeOrder(
  data?: PlaceOrderMutationRequest,
  config: Partial<RequestConfig<PlaceOrderMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PlaceOrderMutationResponse,
    ResponseErrorConfig<PlaceOrder400>,
    PlaceOrderMutationRequest
  >({
    method: 'POST',
    url: getPlaceOrderUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
