/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteOrderPathParams = {
  /**
   * @description ID of the order that needs to be deleted
   * @type integer, int64
   */
  orderId: number;
};

/**
 * @description order deleted
 */
export type DeleteOrder200 = unknown;

/**
 * @description Invalid ID supplied
 */
export type DeleteOrder400 = unknown;

/**
 * @description Order not found
 */
export type DeleteOrder404 = unknown;

/**
 * @description Unexpected error
 */
export type DeleteOrderError = unknown;

export type DeleteOrderMutationResponse = DeleteOrder200;

export type DeleteOrderMutation = {
  Response: DeleteOrder200;
  PathParams: DeleteOrderPathParams;
  Errors: DeleteOrder400 | DeleteOrder404;
};
