/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Order } from '../Order.ts';

/**
 * @description successful operation
 */
export type PlaceOrder200 = Order;

/**
 * @description Invalid input
 */
export type PlaceOrder400 = unknown;

/**
 * @description Validation exception
 */
export type PlaceOrder422 = unknown;

/**
 * @description Unexpected error
 */
export type PlaceOrderError = unknown;

export type PlaceOrderMutationRequest = Order;

export type PlaceOrderMutationResponse = PlaceOrder200;

export type PlaceOrderMutation = {
  Response: PlaceOrder200;
  Request: PlaceOrderMutationRequest;
  Errors: PlaceOrder400 | PlaceOrder422;
};
