/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createCreateUsersWithListInputMutationResponse } from '../../faker/user/createCreateUsersWithListInput.ts';
import type { CreateUsersWithListInputMutationResponse } from '../../model/user/CreateUsersWithListInput.ts';

export function createUsersWithListInputHandler(
  data?:
    | CreateUsersWithListInputMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/user/createWithList', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(
      JSON.stringify(data || createCreateUsersWithListInputMutationResponse(data)),
      {
        status: 200,
      },
    );
  });
}
