/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createCreateUsersWithArrayInputMutationResponse } from '../../faker/user/createCreateUsersWithArrayInput.ts';
import type { CreateUsersWithArrayInputMutationResponse } from '../../model/user/CreateUsersWithArrayInput.ts';

export function createUsersWithArrayInputHandler(
  data?:
    | CreateUsersWithArrayInputMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/user/createWithArray', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(
      JSON.stringify(data || createCreateUsersWithArrayInputMutationResponse(data)),
      {
        status: 200,
      },
    );
  });
}
