/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createCreateUserMutationResponse } from '../../faker/user/createCreateUser.ts';
import type { CreateUserMutationResponse } from '../../model/user/CreateUser.ts';

export function createUserHandlerResponse200(data: CreateUserMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function createUserHandler(
  data?:
    | CreateUserMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/user', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createCreateUserMutationResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
