/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createDeleteUserMutationResponse } from '../../faker/user/createDeleteUser.ts';
import type {
  DeleteUser400,
  DeleteUser404,
  DeleteUserMutationResponse,
} from '../../model/user/DeleteUser.ts';

export function deleteUserHandlerResponse200(data?: DeleteUserMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
  });
}

export function deleteUserHandlerResponse400(data?: DeleteUser400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function deleteUserHandlerResponse404(data?: DeleteUser404) {
  return new Response(JSON.stringify(data), {
    status: 404,
  });
}

export function deleteUserHandler(
  data?:
    | DeleteUserMutationResponse
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response | Promise<Response>),
) {
  return http.delete('/user/:username', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createDeleteUserMutationResponse(data)), {
      status: 200,
    });
  });
}
