/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createLogoutUserQueryResponse } from '../../faker/user/createLogoutUser.ts';
import type { LogoutUserQueryResponse } from '../../model/user/LogoutUser.ts';

export function logoutUserHandlerResponse200(data?: LogoutUserQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
  });
}

export function logoutUserHandler(
  data?:
    | LogoutUserQueryResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response | Promise<Response>),
) {
  return http.get('/user/logout', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createLogoutUserQueryResponse(data)), {
      status: 200,
    });
  });
}
