/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createUpdateUserMutationResponse } from '../../faker/user/createUpdateUser.ts';
import type {
  UpdateUser400,
  UpdateUser404,
  UpdateUserMutationResponse,
} from '../../model/user/UpdateUser.ts';

export function updateUserHandlerResponse200(data?: UpdateUserMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
  });
}

export function updateUserHandlerResponse400(data?: UpdateUser400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function updateUserHandlerResponse404(data?: UpdateUser404) {
  return new Response(JSON.stringify(data), {
    status: 404,
  });
}

export function updateUserHandler(
  data?:
    | UpdateUserMutationResponse
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response | Promise<Response>),
) {
  return http.put('/user/:username', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createUpdateUserMutationResponse(data)), {
      status: 200,
    });
  });
}
