/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type { Category } from '../model/Category.ts';

export const categorySchema = z.object({
  id: z.optional(z.int()),
  name: z.optional(z.string()),
}) as unknown as z.ZodType<Category>;
