/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type { Order } from '../model/Order.ts';

export const orderSchema = z.object({
  id: z.optional(z.int()),
  petId: z.optional(z.int()),
  quantity: z.optional(z.int()),
  shipDate: z.optional(z.iso.datetime({ offset: true })),
  status: z.optional(z.enum(['placed', 'approved', 'delivered']).describe('Order Status')),
  complete: z.optional(z.boolean()),
}) as unknown as z.ZodType<Order>;
