/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type { Pet } from '../model/Pet.ts';
import { categorySchema } from './categorySchema.ts';
import { tagSchema } from './tagSchema.ts';

export const petSchema = z.object({
  id: z.optional(z.int()),
  get category() {
    return categorySchema.optional();
  },
  name: z.string(),
  photoUrls: z.array(z.string()),
  get tags() {
    return z.array(tagSchema).optional();
  },
  status: z.optional(z.enum(['available', 'pending', 'sold']).describe('pet status in the store')),
}) as unknown as z.ZodType<Pet>;
