/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type { Tag } from '../model/Tag.ts';

export const tagSchema = z.object({
  id: z.optional(z.int()),
  name: z.optional(z.string()),
}) as unknown as z.ZodType<Tag>;
