/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type { UserArray } from '../model/UserArray.ts';
import { userSchema } from './userSchema.ts';

export const userArraySchema = z.array(z.lazy(() => userSchema)) as unknown as z.ZodType<UserArray>;
