/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type {
  DeleteOrderMutationResponse,
  DeleteOrderPathParams,
} from '../../model/store/DeleteOrder.ts';

export function createDeleteOrderPathParams(
  data?: Partial<DeleteOrderPathParams>,
): DeleteOrderPathParams {
  return {
    ...{ orderId: faker.number.int() },
    ...(data || {}),
  };
}

/**
 * @description order deleted
 */
export function createDeleteOrder200() {
  return undefined;
}

/**
 * @description Invalid ID supplied
 */
export function createDeleteOrder400() {
  return undefined;
}

/**
 * @description Order not found
 */
export function createDeleteOrder404() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createDeleteOrderError() {
  return undefined;
}

export function createDeleteOrderMutationResponse(
  data?: Partial<DeleteOrderMutationResponse>,
): DeleteOrderMutationResponse {
  return data || faker.helpers.arrayElement<any>([createDeleteOrder200()]);
}
