/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { PlaceOrderMutationResponse } from '../../model/store/PlaceOrder.ts';
import { createOrder } from '../createOrder.ts';

/**
 * @description successful operation
 */
export function createPlaceOrder200() {
  return createOrder();
}

/**
 * @description Invalid input
 */
export function createPlaceOrder400() {
  return undefined;
}

/**
 * @description Validation exception
 */
export function createPlaceOrder422() {
  return undefined;
}

/**
 * @description Unexpected error
 */
export function createPlaceOrderError() {
  return undefined;
}

export function createPlaceOrderMutationRequest() {
  return createOrder();
}

export function createPlaceOrderMutationResponse(
  data?: Partial<PlaceOrderMutationResponse>,
): PlaceOrderMutationResponse {
  return data || faker.helpers.arrayElement<any>([createPlaceOrder200()]);
}
