/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';
import type { GetInventory200, GetInventoryQueryResponse } from '../../model/store/GetInventory.ts';

/**
 * @description successful operation
 */
export function createGetInventory200(data?: Partial<GetInventory200>): GetInventory200 {
  faker.seed([100]);
  return {
    ...{},
    ...(data || {}),
  };
}

export function createGetInventoryQueryResponse(
  data?: Partial<GetInventoryQueryResponse>,
): GetInventoryQueryResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createGetInventory200()]);
}
