/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createDeleteOrderMutationResponse } from '../../faker/store/createDeleteOrder.ts';
import type {
  DeleteOrder400,
  DeleteOrder404,
  DeleteOrderMutationResponse,
} from '../../model/store/DeleteOrder.ts';

export function deleteOrderHandlerResponse200(data?: DeleteOrderMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
  });
}

export function deleteOrderHandlerResponse400(data?: DeleteOrder400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function deleteOrderHandlerResponse404(data?: DeleteOrder404) {
  return new Response(JSON.stringify(data), {
    status: 404,
  });
}

export function deleteOrderHandler(
  data?:
    | DeleteOrderMutationResponse
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response | Promise<Response>),
) {
  return http.delete('/store/order/:orderId', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createDeleteOrderMutationResponse(data)), {
      status: 200,
    });
  });
}
