/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createGetInventoryQueryResponse } from '../../faker/store/createGetInventory.ts';
import type { GetInventoryQueryResponse } from '../../model/store/GetInventory.ts';

export function getInventoryHandlerResponse200(data: GetInventoryQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function getInventoryHandler(
  data?:
    | GetInventoryQueryResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response | Promise<Response>),
) {
  return http.get('/store/inventory', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createGetInventoryQueryResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
