/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createGetOrderByIdQueryResponse } from '../../faker/store/createGetOrderById.ts';
import type {
  GetOrderById400,
  GetOrderById404,
  GetOrderByIdQueryResponse,
} from '../../model/store/GetOrderById.ts';

export function getOrderByIdHandlerResponse200(data: GetOrderByIdQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function getOrderByIdHandlerResponse400(data?: GetOrderById400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function getOrderByIdHandlerResponse404(data?: GetOrderById404) {
  return new Response(JSON.stringify(data), {
    status: 404,
  });
}

export function getOrderByIdHandler(
  data?:
    | GetOrderByIdQueryResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response | Promise<Response>),
) {
  return http.get('/store/order/:orderId', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createGetOrderByIdQueryResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
