/* eslint-disable no-alert, no-console */
// @ts-nocheck
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';
import { createPlaceOrderMutationResponse } from '../../faker/store/createPlaceOrder.ts';
import type { PlaceOrder400, PlaceOrderMutationResponse } from '../../model/store/PlaceOrder.ts';

export function placeOrderHandlerResponse200(data: PlaceOrderMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

export function placeOrderHandlerResponse400(data?: PlaceOrder400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  });
}

export function placeOrderHandler(
  data?:
    | PlaceOrderMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>),
) {
  return http.post('/store/order', function handler(info) {
    if (typeof data === 'function') return data(info);

    return new Response(JSON.stringify(data || createPlaceOrderMutationResponse(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
