/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  GetInventory200,
  GetInventoryError,
  GetInventoryQueryResponse,
} from '../../model/store/GetInventory.ts';

/**
 * @description successful operation
 */
export const getInventory200Schema = z
  .object({})
  .catchall(z.int()) as unknown as z.ZodType<GetInventory200>;

/**
 * @description Unexpected error
 */
export const getInventoryErrorSchema = z.unknown() as unknown as z.ZodType<GetInventoryError>;

export const getInventoryQueryResponseSchema = z.lazy(
  () => getInventory200Schema,
) as unknown as z.ZodType<GetInventoryQueryResponse>;
