/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  GetOrderById200,
  GetOrderById400,
  GetOrderById404,
  GetOrderByIdPathParams,
  GetOrderByIdQueryResponse,
} from '../../model/store/GetOrderById.ts';
import { orderSchema } from '../orderSchema.ts';

export const getOrderByIdPathParamsSchema = z.object({
  orderId: z.coerce.number().int().min(1).max(10).describe('ID of pet that needs to be fetched'),
}) as unknown as z.ZodType<GetOrderByIdPathParams>;

/**
 * @description successful operation
 */
export const getOrderById200Schema = z.lazy(
  () => orderSchema,
) as unknown as z.ZodType<GetOrderById200>;

/**
 * @description Invalid ID supplied
 */
export const getOrderById400Schema = z.unknown() as unknown as z.ZodType<GetOrderById400>;

/**
 * @description Order not found
 */
export const getOrderById404Schema = z.unknown() as unknown as z.ZodType<GetOrderById404>;

export const getOrderByIdQueryResponseSchema = z.lazy(
  () => getOrderById200Schema,
) as unknown as z.ZodType<GetOrderByIdQueryResponse>;
