/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod';
import type {
  PlaceOrder200,
  PlaceOrder400,
  PlaceOrderMutationRequest,
  PlaceOrderMutationResponse,
} from '../../model/store/PlaceOrder.ts';
import { orderSchema } from '../orderSchema.ts';

/**
 * @description successful operation
 */
export const placeOrder200Schema = z.lazy(() => orderSchema) as unknown as z.ZodType<PlaceOrder200>;

/**
 * @description Invalid Order
 */
export const placeOrder400Schema = z.unknown() as unknown as z.ZodType<PlaceOrder400>;

/**
 * @description order placed for purchasing the pet
 */
export const placeOrderMutationRequestSchema = z.lazy(
  () => orderSchema,
) as unknown as z.ZodType<PlaceOrderMutationRequest>;

export const placeOrderMutationResponseSchema = z.lazy(
  () => placeOrder200Schema,
) as unknown as z.ZodType<PlaceOrderMutationResponse>;
